# H2
spring:
  # Datasource
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


    #DIRETORIOS
file:
  directory:
    out: /tmp/output/
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  # Datasource
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  #spring:jpa:hibernate:ddl-auto=create

  #CONFIGURACOES SPRING BATCH
#  batch:
#    job:
#      enabled: true
#    initialize-schema: always

